### PR TITLE
Fix casting exception with`orderby` when using MySQL/PostgreSQL

### LINKED ISSUE #2241: Issue with 'orderby' in query
Hello,
I don't really know if it's a bug or a problem on my side but I'm facing an exception in queries where the "orderby" clause contains fields other than the basic fields (datepublish...)

Details
-------
| Relevant Bolt Version | 4.1.5
| Install type                   | Composer install
| PHP version                 | 7.3.23 |
| Web server                  | Apache

Reproduction
------------

**Query OK:** 
`{% setcontent records = 'articles' where { region:region.id } orderby '-publishedAt' %} `
          
**Query NOK**                             
`{% setcontent records = 'articles' where { region:region.id } orderby 'titre' %}`
Here, 'titre' is a text field. It is the same if I sort with select fields or other filed types.      

These queries are correct with bolt 3.7, but failed with bolt 4.1. This only works when I delete the "orderby" clause or replace it with `orderby -publishedAt`                                

### Actual result

```
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_0 FROM (SELECT b0_.id AS id_0, b0_.content_type AS content_type_1, b0_.status AS status_2, b0_.created_at AS created_at_3, b0_.modified_at AS modified_at_4, b0_.published_at AS published_at_5, b0_.depublished_at AS depublished_at_6 FROM bolt_content b0_ LEFT JOIN bolt_field b1_ ON b0_.id = b1_.content_id AND b1_.type IN ('generic', 'block', 'checkbox', 'collection', 'data', 'date', 'email', 'embed', 'file', 'filelist', 'hidden', 'html', 'image', 'imagelist', 'markdown', 'number', 'select', 'set', 'slug', 'templateselect', 'text', 'textarea', 'article', 'redactor') LEFT JOIN bolt_field_translation b2_ ON b1_.id = b2_.translatable_id LEFT JOIN bolt_field b3_ ON b0_.id = b3_.content_id AND b3_.type IN ('generic', 'block', 'checkbox', 'collection', 'data', 'date', 'email', 'embed', 'file', 'filelist', 'hidden', 'html', 'image', 'imagelist', 'markdown', 'number', 'select', 'set', 'slug', 'templateselect', 'text', 'textarea', 'article', 'redactor') LEFT JOIN bolt_field_translation b4_ ON b3_.id = b4_.translatable_id LEFT JOIN bolt_field b5_ ON b0_.id = b5_.content_id AND b5_.type IN ('generic', 'block', 'checkbox', 'collection', 'data', 'date', 'email', 'embed', 'file', 'filelist', 'hidden', 'html', 'image', 'imagelist', 'markdown', 'number', 'select', 'set', 'slug', 'templateselect', 'text', 'textarea', 'article', 'redactor') LEFT JOIN bolt_field_translation b6_ ON b5_.id = b6_.translatable_id LEFT JOIN bolt_field b7_ ON b0_.id = b7_.content_id AND b7_.type IN ('generic', 'block', 'checkbox', 'collection', 'data', 'date', 'email', 'embed', 'file', 'filelist', 'hidden', 'html', 'image', 'imagelist', 'markdown', 'number', 'select', 'set', 'slug', 'templateselect', 'text', 'textarea', 'article', 'redactor') LEFT JOIN bolt_field_translation b8_ ON b7_.id = b8_.translatable_id LEFT JOIN bolt_field b9_ ON b0_.id = b9_.content_id AND b9_.type IN ('generic', 'block', 'checkbox', 'collection', 'data', 'date', 'email', 'embed', 'file', 'filelist', 'hidden', 'html', 'image', 'imagelist', 'markdown', 'number', 'select', 'set', 'slug', 'templateselect', 'text', 'textarea', 'article', 'redactor') LEFT JOIN bolt_field_translation b10_ ON b9_.id = b10_.translatable_id WHERE b0_.content_type = ? AND ((JSON_EXTRACT(b2_.value, '$[0]') = ? AND b1_.parent_id IS NULL AND b1_.name = ?) AND (JSON_EXTRACT(b4_.value, '$[0]') = ? AND b3_.parent_id IS NULL AND b3_.name = ?) AND (JSON_EXTRACT(b6_.value, '$[0]') = ? AND b5_.parent_id IS NULL AND b5_.name = ?) AND (JSON_EXTRACT(b8_.value, '$[0]') <> ? AND b7_.parent_id IS NULL AND b7_.name = ?) AND b0_.status = ?) AND b9_.name = ? AND b10_.locale = ? ORDER BY LOWER(CAST(b10_.value AS TEXT)) ASC) dctrn_result) dctrn_table' with params ["articles", "188", "region", "published", "titre", "fr"]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'TEXT)) ASC) dctrn_result) dctrn_table' at line 1").
```

### PR DESCRIPTION
**Pull request by I-Valchev**
Fixes #2241

### CODE REVIEW

File: src/Storage/Directive/OrderDirective.php [hunk 1]
```diff
@@ -116,6 +116,8 @@ private function setOrderBy(QueryInterface $query, string $order, string $direct
                 // Note the `lower()` in the `addOrderBy()`. It is essential to sorting the
                 // results correctly. See also https://github.com/bolt/core/issues/1190
                 // again: lower breaks postgresql jsonb compatibility, first cast as txt
+                // cast as TEXT or CHAR, depending on SQL support. See Bolt\Doctrine\Query\Cast.php
+                // and https://github.com/bolt/core/issues/2241
                 $query
                     ->getQueryBuilder()
                     ->addOrderBy('lower(CAST(' . $translationsAlias . '.value as TEXT))', $direction);
```
Comment (bobdenotter) [inline src/Storage/Directive/OrderDirective.php:123]: Shouldn't this `TEXT` also be dependent on the platform, then?

**Review by bobdenotter — CHANGES_REQUESTED** [review]

File: src/Storage/Directive/OrderDirective.php (hunk 1 above)
Comment (bobdenotter) [reply src/Storage/Directive/OrderDirective.php:123]: (As explained by Ivo: No, it shouldn't)

**Review by bobdenotter — APPROVED** [review]
