### PR TITLE
Fix: null author locale when saving new content

### LINKED ISSUE #3696: Call to getLocale() on null originalAuthor when saving new content
## Bug Description

When creating and saving a **new** content record in the Bolt backend, a 500 error is thrown:

```
Call to a member function getLocale() on null
```

**File:** `src/Controller/Backend/ContentEditController.php` (line 184)

## Root Cause

In the `save()` method, when `$originalContent` is `null` (i.e., creating a new record), `$originalAuthor` is set to `null` at line 123:

```php
} else {
    $originalStatus = null;
    $originalPublishedAt = null;
    $originalDepublishedAt = null;
    $originalAuthor = null;
}
```

Then at line 184, `->getLocale()` is called on it without a null check:

```php
$locale = $originalAuthor->getLocale();
```

## Expected Behavior

Saving a new content record should work without errors.

## Suggested Fix

```php
$locale = $originalAuthor ? $originalAuthor->getLocale() : $request->getLocale();
```

## Environment

- Bolt version: **6.0.1**
- PHP: 8.2+
- Symfony: 6.4

## Steps to Reproduce

1. Go to the Bolt backend
2. Create a new content record of any content type
3. Fill in the required fields
4. Click Save
5. 500 error is thrown

### PR DESCRIPTION
**Pull request by MrWeb**
## Summary

- Fix fatal error `Call to a member function getLocale() on null` when saving a **new** content record in the backend
- When `$originalContent` is null (new record), `$originalAuthor` is null — falls back to `$request->getLocale()` instead of crashing

Fixes #3696

## Test plan

- [ ] Create a new content record of any content type
- [ ] Fill in required fields and click Save
- [ ] Verify it saves without 500 error
- [ ] Verify editing an existing record still works correctly

### CODE REVIEW

File: src/Controller/Backend/ContentEditController.php [hunk 1]
```diff
@@ -181,7 +181,7 @@ public function save(Request $request, ?Content $originalContent = null, ?Conten
         $event = new ContentEvent($content);
         $this->dispatcher->dispatch($event, ContentEvent::POST_SAVE);
 
-        $locale = $originalAuthor->getLocale();
+        $locale = $originalAuthor ? $originalAuthor->getLocale() : $request->getLocale();
 
         // If we're "Saving Ajaxy"
         if ($request->isXmlHttpRequest()) {
```
Comment (bobvandevijver) [inline src/Controller/Backend/ContentEditController.php]:
```suggestion
        // If we're "Saving Ajaxy"
        if ($request->isXmlHttpRequest()) {
            $locale = $originalAuthor ? $originalAuthor->getLocale() : $request->getLocale();
```

Let move it inside the condition, as it is only used there.

**Review by bobvandevijver — CHANGES_REQUESTED** [review]
Can you make sure that all checks (except for the cypress one, that is broken once agani) are passing?

**Comment by MrWeb** [comment]
Dear @bobvandevijver, done, all passed buy Cypress.

**Review by bobvandevijver — APPROVED** [review]

**Comment by bobvandevijver** [comment]
Thanks @MrWeb!
