### PR TITLE
Fix upload from url

### LINKED ISSUE #3225: Upload image from URL does not work on imagelists
Uploading an image from Url on an imagelist field does not upload the image and throws an error in the console.

image

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.1.9
| Install type                                          |  Composer install 
| PHP version                                           | 7.4 |
| Web server                                            | Apache

Reproduction
------------

Upload an image from URL in an imagelist field.

### Expected result

Upload image from URL in imagelist field

### Actual result

Error thrown in console while uploading image from URL.

### LINKED ISSUE #3226: Selecting images from library results in wrong path to image, related with issue #3225
When selecting an image from the library. This results in the following incorrect path to the image. Insering multiple forward slashes.

Capture_image_widget

When attempting several times to remove the incorrect entry and trying again this results in the 'from library' button getting greyed out.

Capture_borkk

Attemping to add the filepath manually via 'from URL' results in issue #3225 and receiving the following message

Capture_limit

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.1.9
| Install type                                          |  Composer install
| PHP version                                           | 7.4
| Web server                                            | Symfony

### PR DESCRIPTION
**Pull request by nestordedios**
This PR fixes:
- Missing input field to upload an image from URL
- Console error that appear when opening and closing the modal to upload an image from a URL

On this branch I can't reproduce #3225 and #3226 so updating to the latest Bolt version should get those fixed.

Fixes #3225 and fixes #3226

### CODE REVIEW

File: assets/js/app/editor/Components/Image.vue [hunk 1]
```diff
@@ -531,7 +530,10 @@ export default {
             var modalBody = resourcesModal.querySelector('.modal-body');
             var modalBodyContent = this.generateUploadFromURLModalContent();
             modalTitle.innerHTML = title;
-            modalBody.innerHTML = modalBodyContent;
+
+            setTimeout(() => {
+                modalBody.innerHTML = modalBodyContent;
+            }, 1)
```
Comment (bobdenotter) [inline assets/js/app/editor/Components/Image.vue:536]:
```suggestion
            }, 1);
```

**Review by bobdenotter — APPROVED** [review]
Whoop! 👍
