### PR TITLE
Sorting correctly for MySQL

### LINKED ISSUE #1190: Unexpected results on Contenttype sorting
**Backend:**

- Sorting contenttypes on defined fields (eg `sort: title`) shows unexpected results. it is not apparent what sort is being based on.

- Sorting contenttypes using columns in Bolt_content table (eg `sort: id`, `sort: -createdAt`) works and gives correct results. 

**Frontend:**

- Listing.twig  - sort defaults to `sort: id` regardless of what is set in the `contenttype.yaml`.

- `{% setcontent entries = 'entries' orderby 'title' %}` also does not show correctly sorted results. This replicates the problems encountered at the backend. 

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version |  4.0.0 rc 6 / rc 7
| Install type                   |  Composer install 
| BC Break                     | no
| PHP version                 |  7.4 
| Web server                  | Apache 
| For UX/UI issues        | n/a

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

As above

### Specifics

screen shot 1: incorrect sort order using defined field
screenshot_1

screen shot 2: correct sort order using id, created date etc
screenshot 2

### Expected result

Ability to sort results based on defined fields of contenttype.

### LINKED ISSUE #1192: Sorting config does _NOT_ sort on frontend
The `sort` contenttypes.yaml config does not sort the records in the frontend, but it should.

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes #1190 
Fixes #1192

### CODE REVIEW

File: src/Controller/Frontend/ListingController.php [hunk 1]
```diff
@@ -44,8 +44,12 @@ public function listing(ContentRepository $contentRepository, Request $request,
         $contentType = ContentType::factory($contentTypeSlug, $this->config->get('contenttypes'));
         $page = (int) $request->query->get('page', 1);
         $amountPerPage = $contentType->get('listing_records');
+        $order = $contentType->get('sort');
```
Comment (JTNMW) [inline src/Controller/Frontend/ListingController.php]: $order = $request->query->get('order', $contentType->get('sort'));

**Comment by JTNMW** [comment]
check if 'order' is set in the request first and if not default back to 'sort' config. 
$order = $request->query->get('order', $contentType->get('sort'));

Im not sure if this works correctly across the entire app, but this would be a preferred option if you can build this in.

**Comment by bobdenotter** [comment]
> check if 'order' is set in the request first and if not default back to 'sort' config.
> $order = $request->query->get('order', $contentType->get('sort'));

I've added this in the PR. Good suggestion! 👍
